BLAZE_BUILD_TYPE ?= UNOFFICIAL

BLAZE_REVISION = 4.1
BLAZE_SUBREVISION := BETA
BLAZE_DATE_YEAR := $(shell date -u +%Y)
BLAZE_DATE_MONTH := $(shell date -u +%m)
BLAZE_DATE_DAY := $(shell date -u +%d)
BLAZE_DATE_HOUR := $(shell date -u +%H)
BLAZE_DATE_MINUTE := $(shell date -u +%M)
BLAZE_BUILD_DATE_UTC := $(shell date -d '$(BLAZE_DATE_YEAR)-$(BLAZE_DATE_MONTH)-$(BLAZE_DATE_DAY) $(BLAZE_DATE_HOUR):$(BLAZE_DATE_MINUTE) UTC' +%s)
BLAZE_BUILD_DATE := $(BLAZE_DATE_YEAR)$(BLAZE_DATE_MONTH)$(BLAZE_DATE_DAY)-$(BLAZE_DATE_HOUR)$(BLAZE_DATE_MINUTE)

BLAZE_VERSION := Blaze-AOSP-$(BLAZE_REVISION)-$(BLAZE_SUBREVISION)-$(BLAZE_BUILD_TYPE)-$(BLAZE_BUILD)-$(BLAZE_BUILD_DATE)
BLAZE_VERSION_PROP := $(BLAZE_REVISION)-$(BLAZE_SUBREVISION)
